### ISSUE TITLE
LICENSING ISSUE

### ISSUE THREAD

**Issue by Vawlpe** [KarmyDev/WebLab#3]
It seems currently that the repository does not have a proper software license, this coupled with implicit copyright law means that to add a proper license we need the explicit permission of every contributor...

I suggest creating a `new` branch from the ***initial commit***
- ~~Then @KarmyDev and @TheHattedKid can ***co-sign*** a commit that adds a `LICENSE` file on this `new` branch,~~
  Edit: I believe @TheHattedKid has to sign the commit, not @KarmyDev (lol)
    and in the extended commit message write a little note about agreeing to it.
- Then simply rebase `main` onto this `new` branch,
- change the primary branch of the repo on gh to the `new` one,
- delete the old `main`,
- and rename `new` to `main`.

This would result in the repository being properly licensed troughout it's entire history, with all the :sparkles: legal mumbo-jumbo :sparkles: dealt with (lol)

~~pls karmy license ur code right away next time, sorry for the intrusion..~~

**Comment by KarmyDev** [comment]
Currently working on it
~~and yes, i will be more cautious next time~~

**Comment by TheHattedKid** [comment]
Thanks, gonna do a PR.

**Comment by KarmyDev** [comment]
Alright. Closing this issue since it's already fixed.
Thanks @Vawlpe for the notice and @TheHattedKid for the agreement.
